### ISSUE TITLE
Doesn't work in node > 0.10

### ISSUE THREAD

**Issue by soycode** [davejamesmiller/generator-licensetxt#1]
Fails to build/install, on OSX at least (the actual error message is a rather abstruse `Failed at the ffi@1.2.5 install script 'node-gyp rebuild'.`). I believe this is due to the dependency on https://github.com/jeremyfa/node-exec-sync (which itself depends on ffi). exec-sync is now a built-in feature for node>=0.12 (https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options).

**Comment by davejamesmiller** [comment]
I probably should have done it asynchronously, but it was my first Node project so I didn't know better. It was just a Hello World type project so I'm not maintaining it any more. You might have more luck with https://www.npmjs.com/package/generator-license. Thanks for your interest though.

**Comment by soycode** [comment]
Makes sense, and agreed there are alternatives - just wanted to let you know. If you don't intend to fix (which is fine) then I'd suggest maybe updating the README to note that this isn't actively maintained. Thanks!

**Comment by davejamesmiller** [comment]
Done, thanks.
